INSERT INTO rdi_version (version_name) VALUES ('The Red Dragon Inn');
INSERT INTO rdi_version (version_name) VALUES ('The Red Dragon Inn');
INSERT INTO rdi_version (version_name) VALUES ('The Red Dragon Inn 3');
INSERT INTO rdi_version (version_name) VALUES ('The Red Dragon Inn 4');
INSERT INTO rdi_version (version_name) VALUES ('The Red Dragon Inn 5');
INSERT INTO rdi_version (version_name) VALUES ('The Red Dragon Inn 6');
INSERT INTO rdi_version (version_name) VALUES ('The Red Dragon Inn 7');
INSERT INTO rdi_version (version_name) VALUES ('The Red Dragon Inn: Allies');
INSERT INTO rdi_version (version_name) VALUES ('The Red Dragon Inn: Munchkin');

INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (9,'Deirdre the Priestess', 'Elf', 'Priestess', 'The Goddess keeps Deirdre protected from harm.', 'The Goddess’s protection does not help against alcohol. Deirdre is a cheap date.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (9, 'Fiona the Volatile', 'Human', 'Fighter', 'She’s more than capable of dishing out and taking serious physical abuse, and her formidable constitution allows her to drink a lot!', 'For all her strengths, she’s not very good at keeping track of her Gold.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (9, 'Gerki the Sneak', 'Hafling', 'Thief', 'Gerki is so good at gambling that some people suspect that he might be cheating.', 'Yeah, he’s cheating.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (9, 'Zot the Wizard', 'Human', 'Wizard', 'Zot is good at card tricks, and, hence, is good at gambling. His mastery of many magical spells keeps him well protected, whether he’s roughhousing, drinking, or gambling.', 'That rabbit is insane. Seriously.');

INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (1, 'Gog the Half Ogre', 'Half-Ogre', 'Barbarian', 'Gog is really Strong!', '“Sorry! Gog Not Know Own Strength.”');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (1, 'Fleck the Bard', 'Half-Elf', 'Bard', 'Women want him, Men want to be him.', 'Sometimes… well okay, often… it goes to his head.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (1, 'Eve the Illusionist', 'Human', 'Illusionist', 'Eve is a very skilled Illusionist.', 'She’s been known to use her skills on her fellow party members when she gets bored.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (1, 'Dimli the Dwarf', 'Dwarf', 'Fighter', 'He’s got a lot of Gold and can pretty much drink anyone under the table!', 'Sometimes, he gets a little grumpy…');

INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (2, 'Wizgille the Tinkerer', 'Gnome', 'Artificer', 'Many of her creations are legendary among the Gnomish Inventors Guild and have been featured in Adventurer’s Gazette.', 'She thinks that a crowded tavern is an appropriate place to test new prototypes.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (2, 'Brewmaster Phrenk', 'Troll', 'Alchemist', 'He’s more than capable of brewing enough healing potions to keep his companions on their feet.', 'He’s just as capable of brewing enough drinks to knock them all back down.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (2, 'Kaylin the Renegade', 'Pixie', 'Enchanter', 'Wulfric is a noble companion who always helps his friends.', 'Kaylin isn’t always so noble.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (2, 'Serena the Pious', 'Orc', 'Paladin', 'With her holy blade at her side, she lives to smite evil.', 'Carousing in a tavern isn’t exactly the best way for Serena to stay on that righteous path…');

INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (3, 'Captain Whitehawk', 'Human', 'Sailor', 'Captain Whitehawk is a brilliant judge of character and quick to action in any scenario.', 'Be careful… things can get violent if anyone insults her ship or her crew.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (3, 'First Mate Remy', 'Drence', 'Fighter', 'Remy keeps an eye on the crew and makes sure ne’er-do-wells get their comeuppance.', 'If you’re a ne’er-do-well, Remy’s got some comeuppance for you.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (3, 'Bryn the Boatswain', 'Human', 'Sailor', 'She’s strong enough to carry a cannon.', 'She’s strong enough to carry a cannon!');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad, worse) VALUES (3, 'Tara the Navigator', 'Human', 'Seer', 'She can tell you your future.', 'It’s never a good idea to know too much about that.', 'She’s going to tell you anyway.');

INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (4, 'Sera the Fleetfooted', 'Human', 'Rogue', 'She hones her skills by sparring with her friends.', 'Sometimes she does this without warning them first…');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (4, 'Lizwick the Collector', 'Gnome', 'Rogue', 'Lizwick’s collection is the envy of academies, guilds and hoarders alike!', '…and they’d like their stuff back.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (4, 'Joran the Trickster', 'Human', 'Mage', 'Joran’s talent for misdirection makes him the perfect weapon against enemy spell-casters.', 'It also makes him the perfect weapon against his friends’ gold, their sobriety, their patience…');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (4, 'Zakhan the Drunken Master', 'Half-Elf', 'Monk', 'Zakhan’s drunken fighting techniques make him a formidable foe.', 'Sometimes he’s actually just drunk.');

INSERT INTO rdi_characters (version_id, character_name, race, class, bad, worse) VALUES (5, 'Daareka the Mindbreaker', 'Deep One', 'Mentalist', 'This femme fatale makes sure you make all the right choices in life.', 'She’s the one making the decisions for you.');
INSERT INTO rdi_characters (version_id, character_name, race, class, bad, worse) VALUES (5, 'Baron von Vlazlo', 'Human', 'Vampire', 'He’s not looking for a pint of ale.', ' “Don’t vorry. It’s joost a nibble.”');
INSERT INTO rdi_characters (version_id, character_name, race, class, bad, worse) VALUES (5, 'Amundyr the Cursed', 'Elf', 'Mummy', 'Her pet scarabs help her take care of those greedy dungeon-delvers.', 'Those scarabs can give you a bad case of mummy rot.');
INSERT INTO rdi_characters (version_id, character_name, race, class, bad, worse) VALUES (5, 'Torglesnarf Duncleton, First of His Name', 'Goblin', 'King', 'Torglesnarf isn’t particularly intimidating or powerful.', 'He is, however, clever enough to hire thugs who are!');

INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (6, 'Warthorn Redbeard', 'Dwarf', 'Businessman', 'Warthorn knows a bit about almost everything!', '…and he’ll happily talk your ear off about it!');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (6, 'Molly the Stablehand', 'Halfling', 'Laborer', 'Molly’s made friends with a whole menagerie of magical and mundane mounts!', 'They’re not always friends with each other… or the furniture… or you…');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (6, 'Jasper the Bouncer', 'Human', 'Mage', 'Jasper keeps folks from sneak-thievin’ the customers.', 'He does, however, frequently lose track of his teeth.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (6, 'The Wench!', 'Human', 'Waitress', 'The special reserve drinks are some of the best in the land!', 'The special reserve drinks are some of the most potent in the land!');

INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Pooky the Vicious', 'Magical', 'Familiar', 'In the dungeon, Pooky’s psychotic behavior has gotten the party out of some pretty nasty jams.', 'That rabbit is even more insane without Zot’s influence. Seriously.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Erin the Ever-Changing', 'Elf', 'Druid', 'Erin’s always ready with a kind word and a healing chant to smooth ruffled feathers or mend wounded flesh.', 'When the drinks start flowing, Erin can turn into a tree. Have you ever tried out-drinking a tree? It’s not pretty.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Cormac the Mighty', 'Human', 'Barbarian', 'Cormac adheres to the ancient traditions of barbarian honor.', 'He also adheres to the ancient traditions of barbarian violence!');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Witchdoctor Natyli', 'Troll', 'Shaman', 'Natyli has a doll for each party member and uses them in the dungeons to enhance her friends’ abilities.', 'Those dolls…? She’s still got them at the tavern…');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Ozrick the Adept', 'Human', 'Elementalist', 'Ozrik’s phenomenal control of the elements is useful versus undead, monstrous humanoids, and other evil dungeon dwellers.', 'Side effects for Ozrik’s companions may include spontaneous combustion, static discharge, and clammy hands.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Brother Bastian', 'Human', 'Cleric', 'Brother Bastian knows many powerful prayers and knows exactly when to use each one.', 'Unfortunately, because he knows so many prayers, you never know what he’s planning next.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Wrench', 'Kobold', 'Artificer', 'He can quickly build gizmos that can do amazing things.', 'Those gizmos are very fragile!');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Zariah the Summoner', 'Human', 'Mage', 'Those summons are soooo cuuute!!!', 'When they combine to form the fearsome Chimera, you’ll be looking for the nearest exit!');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Halden the Unhinged', 'Human', 'Shaman', 'Halden can draw on the wisdom and power of countless lifetimes.', 'His totems would like to remind you that he isn’t making up the voices in his head.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Keet', 'Goblin ', 'Archaeologist', 'Many of the artifacts Keet has dug up belong in a museum!', '… but many of them end up as tips for the Wench.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Nitrel', 'Goblin', 'Sapper', 'She knows exactly the right amount of explosive for the job.', 'Sometimes she uses more just for fun!');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'The Magnificent Adonis, Bard of the Ages', 'Human', 'Bard', 'Adonis is a fine specimen of a man.', '… and he won’t let you forget it!');
INSERT INTO rdi_characters (version_id, character_name, race, class, bad, worse) VALUES (7, 'The Lich King', 'Lich', 'Mage', ' Good luck getting past his formidable defenses.', 'He knows how to “throw a punch.” Literally.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Ohava, the Grand Cleric', 'Elf', 'Grand Cleric', 'The blessings of the All-Mother are a powerful incentive to Ohava’s good works.', 'Getting four fickle deities to agree on anything takes a LOT of convincing.');
INSERT INTO rdi_characters (version_id, character_name, race, class, bad, worse) VALUES (7, 'Murgath the Blessed', 'Human', 'Blackguard', 'Murgath is a fearsome enemy.', 'He is this powerful even with Banefall holding him back!');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (7, 'Chronos the Time Mage', 'Human', 'Mage', 'He’s always very careful to avoid messing with the space-time continuum.', 'After a few drinks, who cares about all that timey-wimey stuff?');

INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (8, 'Flower', 'Human', 'Munchkin', 'The tavern’s new patrons are eager to make a good impression.', 'It isn’t working.');
INSERT INTO rdi_characters (version_id, character_name, race, class, good, bad) VALUES (8, 'Spyke', 'Human', 'Munchkin', 'The tavern’s new patrons are eager to make a good impression.', 'It isn’t working.');